// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tsqmbxjnzrngwzrfjfcz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzcW1ieGpuenJuZ3d6cmZqZmN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MjcyODUsImV4cCI6MjA3MjQwMzI4NX0.7RW2b7jN9FW_aPUD1Nrv9IVrAOsmnjiVc6fvcm3S-4A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});